"""The graded functional ``preprocessing_test`` — the end-to-end acceptance gate (#61).

Unlike the unit tests (which check one function at a time with fakes), this drives the
**real** ``scripts/preprocess.py`` on a sample clip through the whole pipeline (capture,
detect, crop, center, 48x48 grayscale, save) and asserts the deliverable contract:
a >=20-second face video yields **>=20** correctly-formatted images.

Config-aware (CONTRIBUTING section 3): it loads the real ``config.yaml`` so a changed
``preprocessing.image_size`` or ``preprocessing_test.min_images`` is picked up here, and
only loosens Haar sensitivity for the *synthetic* fixture face (a real face is detected
with the shipped params). The sample clip is generated by a fixture, not a commit, so
the test stays offline, deterministic, and free of a binary in the repo.

**On "contains a face":** re-running the detector on a tight 48x48 crop is unreliable
(the face fills the frame, below Haar's minimum), so the face guarantee is enforced
where it holds: the pipeline only saves a frame after detecting a face in it, and each
saved crop is verified non-blank. The real-detector path is covered in
``tests/test_preprocess.py``.
"""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path

import numpy as np
import pytest

cv2 = pytest.importorskip("cv2")

_SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "preprocess.py"


def _load_preprocess_script():
    spec = importlib.util.spec_from_file_location("preprocess_script", _SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _draw_face(img: np.ndarray) -> None:
    cv2.ellipse(img, (150, 160), (80, 100), 0, 0, 360, (150, 150, 150), -1)
    cv2.circle(img, (120, 140), 12, (50, 50, 50), -1)
    cv2.circle(img, (180, 140), 12, (50, 50, 50), -1)
    cv2.ellipse(img, (150, 175), (8, 18), 0, 0, 360, (110, 110, 110), -1)
    cv2.ellipse(img, (150, 210), (30, 12), 0, 0, 360, (70, 70, 70), -1)


def _make_face_video(path: Path, frames: int, fps: float) -> None:
    writer = cv2.VideoWriter(
        str(path), cv2.VideoWriter_fourcc(*"mp4v"), fps, (300, 300)
    )
    for _ in range(frames):
        img = np.full((300, 300, 3), 200, np.uint8)
        _draw_face(img)
        writer.write(img)
    writer.release()


def _video_io_works(tmp_path: Path) -> bool:
    probe = tmp_path / "_probe.mp4"
    try:
        _make_face_video(probe, frames=3, fps=3.0)
        cap = cv2.VideoCapture(str(probe))
        ok = cap.isOpened() and cap.read()[0]
        cap.release()
        return bool(ok)
    except Exception:
        return False


def _cascade_available() -> bool:
    return hasattr(cv2, "CascadeClassifier") and os.path.exists(
        os.path.join(cv2.data.haarcascades, "haarcascade_frontalface_default.xml")
    )


@pytest.fixture()
def sample_clip(tmp_path: Path) -> Path:
    """A ≥20-second face clip (25 frames @ 1 fps) — the functional test's input."""
    if not _video_io_works(tmp_path):
        pytest.skip("OpenCV video backend can't round-trip a file here")
    path = tmp_path / "face_25s.mp4"
    _make_face_video(path, frames=25, fps=1.0)  # 25 seconds of a visible face
    return path


@pytest.fixture()
def functional_cfg(tmp_path):
    """Real config.yaml, with Haar sensitivity loosened for the synthetic fixture."""
    script = _load_preprocess_script()
    cfg = script.load_config("config.yaml")
    # Synthetic faces need looser Haar than the production defaults; a real face is
    # detected with the shipped params. Everything else stays as configured.
    cfg["face_detector"]["scale_factor"] = 1.05
    cfg["face_detector"]["min_neighbors"] = 3
    cfg["paths"]["preprocessing_test_dir"] = str(tmp_path / "out")
    return cfg


@pytest.mark.skipif(not _cascade_available(), reason="OpenCV Haar cascade unavailable")
def test_preprocessing_test_yields_at_least_20_formatted_faces(
    functional_cfg, sample_clip
) -> None:
    script = _load_preprocess_script()
    size = int(functional_cfg["preprocessing"]["image_size"])  # config-driven (48)
    min_images = int(functional_cfg["preprocessing_test"]["min_images"])  # 20

    saved = script.run_preprocess(functional_cfg, video_path=str(sample_clip))

    out_dir = Path(functional_cfg["paths"]["preprocessing_test_dir"])
    images = sorted(out_dir.glob("image*.png"))
    assert saved >= min_images  # the deliverable contract: >= 20 from a >= 20s clip
    assert len(images) == saved
    # sequential filenames image0.png .. imageN.png
    assert (out_dir / "image0.png").exists()
    assert (out_dir / f"image{saved - 1}.png").exists()

    for image_path in images:
        img = cv2.imread(str(image_path), cv2.IMREAD_UNCHANGED)
        assert img.shape == (size, size)  # 48×48, single channel (grayscale)
        assert img.dtype == np.uint8
        assert img.std() > 0  # a real face crop, not a blank frame
